### PR TITLE
Add script to load local keystore file to db

### PR DESCRIPTION
**Pull request by Remagpie**

### CODE REVIEW

**Comment by Kais-DkM** [comment]
@majecty Agreed. 
What do you think about the behavior after finding the key?
Should we just skip it or rollback the entire procedure?

**Comment by majecty** [comment]
IMO, checking the HD wallet keys first and canceling all procedure if the check failed is better.

**Comment by majecty** [comment]
@Remagpie Let's merge this PR.

**Comment by Remagpie** [comment]
We didn't implement the HD wallet related feature yet.
Would it be better to leave an issue for that?

**Comment by majecty** [comment]
OK

**Pull request merged**
